source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'xflowapp.xcodeproj'
link_with ['xflowapp']

target 'xflowapp', :exclusive => true do
  pod "xflowapp", :path => "../"
  pod  "xflowparser", :git  => "https://github.com/xflow/xflowparser.git"
end
:
target 'Tests', :exclusive => true do
  pod "xflowapp", :path => "../"
  pod  "xflowparser", :git  => "https://github.com/xflow/xflowparser.git"
  pod 'OCMock', '~> 2.2.4'
end
: