target 'xflowapp', :exclusive => true do
  pod "xflowapp", :path => "../"
  pod 'CocoaLumberjack', '~> 1.9.1'
end

target 'Tests', :exclusive => true do
  pod "xflowapp", :path => "../"
  pod 'OCMock', '~> 2.2.4'
  pod 'Kiwi/XCTest'
  pod 'FBSnapshotTestCase'
end

pod 'Aspects', '~> 1.4.1'
